== Classes overview

This project contains 1 classe and 0 interface.

.Classes list
[cols="", %autowidth, frame=all, grid=all, stripes=none]
|===
|Classes |Interfaces

|<<Transport.lvclass>>
|
|===

[plantuml, format="svg", align="center"]
....
@startuml
set namespaceSeparator :
skinparam ClassBackgroundColor #FFFFFF
skinparam ClassBorderColor #555555
skinparam ClassFontColor #000000
skinparam ClassHeaderBackgroundColor #808080

skinparam top to bottom direction
class "Transport" {
{field} +Dependencies : Cluster
{field} -Notifier : NoType
{field} -Sweep Configuration : Cluster
{static} {method} -Calculate R and G (Four Terminal)()
{static} {method} -Calculate R and G (Two Terminal)()
{static} {method} -Calculate R and G 2()
{static} {method} -Graph R and G vs Parameter()
{static} {method} -Graph Lockin vs Parameter()
{static} {method} -Results (Dictionary) to X and Y Arrays()
{static} {method} -Results (2D) to X and Y Arrays()
{static} {method} -Exec State to Append()
{static} {method} -State History()
{static} {method} +Lockin_AIWFM_time()
{static} {method} +Sweep_AIWFM_time()
{static} {method} +Lockin_time()
{static} {method} +Lockin_sweep()
{static} {method} +THz_TimeDelay()

}
"Transport" *-- "Control Experiment"



@enduml
....
